export const first = [
    {
      icon: 'Odometer',
      index: '/qnworkbenchHome',
      title: '首页',
      permiss: '1',
    },
    { // test
      icon: 'Odometer',
      index: '',
      title: '商品--',
      permiss: '2',
    },
    {
      icon: 'Odometer',
      index: '/tradePlatform',
      title: '交易',
      permiss: '3',
    },
    {
      icon: 'Odometer',
      index: '/privateDomainWorkbench',
      title: '私域',
      permiss: '4',
    },
    {
      icon: 'Odometer',
      index: '/contentCenter',
      title: '内容',
      permiss: '5',
    },
    {
      icon: 'Odometer',
      index: '/shopManage',
      title: '店铺',
      permiss: '6',
    },
    {
      icon: 'Odometer',
      index: '/qnTmcSeller',
      title: '营销',
      permiss: '7',
    },
    { // test
      icon: 'Odometer',
      index: '',
      title: '推广--',
      permiss: '8',
    },
    { // test
      icon: 'Odometer',
      index: '',
      title: '客服--',
      permiss: '9',
    },
    { // test
      icon: 'Odometer',
      index: '',
      title: '财务--',
      permiss: '10',
    },
    {
      icon: 'Odometer',
      index: '/data',
      title: '数据',
      permiss: '11',
    },
    { // test
      icon: 'Odometer',
      index: '',
      title: '服务--',
      permiss: '12',
    },
    { // test
      icon: 'Odometer',
      index: '',
      title: '应用--',
      permiss: '13',
    },
  ];